spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monitoring
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      default_schema: monitoring_db
  flyway:
    locations: classpath:db/migration
    schemas: monitoring_db
#  sql:
#    init:
#      schema-locations:
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type: TRACE